version: '3.8'

services:
  app:
    build: .
    container_name: adms-go
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - TZ=Asia/Jakarta
      - DB_ADMS_DSN=root:@tcp(mariadb:3306)/java_adms?parseTime=true
    restart: unless-stopped
